ProyecPOC/Controllers/PymesController.cs
// ++++++++++++++++++++++++++++++++++++++++++++++++++
// This code is generated by a tool and is provided "as is", without warranty of any kind, 
// express or implied, including but not limited to the warranties of merchantability, 
// fitness for a particular purpose and non-infringement.
// In no event shall the authors or copyright holders be liable for any claim, damages or
// other liability, whether in an action of contract, tort or otherwise, arising from,
// out of or in connection with the software or the use or other dealings in the software.
// ++++++++++++++++++++++++++++++++++++++++++++++++++









using System.Linq;
using System.Web.Mvc;
namespace ProyecPOC.Controllers
{
	public class PymesController : Controller
	{
		private ProyecPOC.Models.BDPOC db = new ProyecPOC.Models.BDPOC();

		//
		// GET: /pymes/

		public ActionResult Index()
		{
			return View(db.pymes.ToList());
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}
	}
}

ProyecPOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>PymesOnlineChile</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-primary">
		<a class="navbar-brand">Pymes Online Chile</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="~/Home/Index">Inicio <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Categorias
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="~/Home/Servicio">Servicios</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="~/Home/Restaurante">Restaurantes</a>
						<a class="dropdown-item" href="~/Home/Tienda">Tiendas</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="~/Pymes/Index">Lista de Pymes</a>
				</li>
				
			</ul>
			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
				<button class="btn btn-success my-2 my-sm-0" type="submit">Buscar</button>
			</form>
		</div>
	</nav>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				
			</div>
			@*<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
					<li>@Html.ActionLink("Tiendas", "Tienda", "Home")</li>
					<li>@Html.ActionLink("Restaurantes", "Restaurante", "Home")</li>
					<li>@Html.ActionLink("Servicios", "Servicio", "Home")</li>
					<li>@Html.ActionLink("Lista de Pymes", "Index", "Pymes")</li>
				</ul>
			</div>*@
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year -Pymes Online Chile- </p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>